name: shakti
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  firebase_storage: ^12.4.3
  cloud_firestore: ^5.6.4
  get: ^4.7.2
  go_router: ^14.8.0
  fpdart: ^1.1.1
  image_picker: ^1.1.2
  path: ^1.9.1
  shared_preferences: ^2.5.2
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - lib/assets/
    - lib/assets/brand/
    - lib/assets/fonts/
