name: shakti
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  firebase_storage: ^12.4.3
  cloud_firestore: ^5.6.4
  get: ^4.7.2
  go_router: ^14.8.0
  fpdart: ^1.1.1
  image_picker: ^1.1.2
  path: ^1.9.1
  shared_preferences: ^2.5.2
  google_sign_in: ^6.2.2
  flutter_slidable: ^4.0.0
  syncfusion_flutter_calendar: ^28.2.12
  syncfusion_flutter_charts: ^28.2.12
  sf_symbols: ^0.2.0
  intl: ^0.20.2
  flutter_sficon: ^1.1.2
  logger: ^2.5.0
  introduction_screen: ^3.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/brand/
    - assets/fonts/
    - assets/introduction/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ThinItalic.ttf
          weight: 100
          style: italic
