// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs85xFHvKTdbCO2qL_czGF-XhDqkwxLBY',
    appId: '1:644449634249:android:388451fe7e78155f1f4a18',
    messagingSenderId: '644449634249',
    projectId: 'shakti-99f2e',
    storageBucket: 'shakti-99f2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKYlLisoWTWkQS610RTFrcJKU4sclJclg',
    appId: '1:644449634249:ios:9540d5b3c58820481f4a18',
    messagingSenderId: '644449634249',
    projectId: 'shakti-99f2e',
    storageBucket: 'shakti-99f2e.firebasestorage.app',
    androidClientId: '644449634249-osgcs3dua8qjiaemvg9n490bq4j48ull.apps.googleusercontent.com',
    iosClientId: '644449634249-bd242g1vls77sgf4o2eqn1mkmebp0s8n.apps.googleusercontent.com',
    iosBundleId: 'com.example.shakti',
  );

}